<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Generated by Codia AI</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Montserrat:wght@800&display=swap" />
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Instrument+Sans:wght@500;700&display=swap" />
    <link rel="stylesheet" href="index.css" />
  </head>
  <body>
    <div class="main-container">
      <div class="rectangle"></div>
      <span class="sign-up-text">SIGN UP</span
      ><span class="account-sign-in">Have an account? Sign In</span
      ><span class="email">Email</span>
      <div class="rectangle-1"></div>
      <span class="username">Username</span>
      <div class="rectangle-2"></div>
      <span class="password">Password</span>
      <div class="rectangle-3"></div>
      <span class="confirm-password">Confirm Password</span>
      <div class="rectangle-4"></div>
      <div class="rectangle-5"><span class="sign-up-6">Sign Up</span></div>
      <span class="or-sign-up-with">Or sign up with</span>
      <div class="line"></div>
      <div class="line-7"></div>
      <div class="rectangle-8">
        <div class="social-icons"><div class="vector"></div></div>
        <span class="continue-with-google">Continue With Google</span>
      </div>
    </div>
    <!-- Generated by Codia AI - https://codia.ai/ -->
  </body>
</html>
