<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Generated by Codia AI</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Montserrat:wght@800&display=swap" />
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Instrument+Sans:wght@500&display=swap" />
    <link rel="stylesheet" href="{{ asset(path: 'css/storagepage.css') }}" />
  </head>
  <body>
    <div class="main-container">
      <div class="rectangle">
        <div class="rectangle-1"><span class="logo">logo</span></div>
        <div class="basket-alt-light"></div>
        <span class="contact-us">Contact us</span
        ><span class="services">Services</span>
        <div class="empty"></div>
        <div class="empty-2"></div>
        <div class="empty-3"></div>
        <div class="empty-4"></div>
        <span class="recipes">Recipes</span><span class="storage">Storage</span
        ><span class="user">User</span>
        <div class="vector"></div>
        <span class="home">Home</span>
      </div>
      <span class="welcome-to-storage">WELCOME TO YOUR STORAGE</span>
      <div class="flex-row-ad">
        <div class="rectangle-5">
          <div class="add-round-light"></div>
          <span class="tambah-bahan">Tambah Bahan</span>
        </div>
        <div class="rectangle-6">
          <div class="image"></div>
          <div class="line"></div>
          <span class="sawi">Sawi</span>
        </div>
        <div class="rectangle-7">
          <div class="image-8"></div>
          <div class="line-9"></div>
          <span class="terong">Terong</span>
        </div>
        <div class="rectangle-a">
          <div class="image-b"></div>
          <div class="line-c"></div>
          <span class="paprika">Paprika</span>
        </div>
        <div class="rectangle-d">
          <div class="image-e"></div>
          <div class="line-f"></div>
          <span class="bawang-putih">Bawang Putih</span>
        </div>
      </div>
      <div class="flex-row-fe">
        <div class="rectangle-10">
          <div class="image-11"></div>
          <div class="line-12"></div>
          <span class="kubis">Kubis</span>
        </div>
        <div class="rectangle-13">
          <div class="image-14"><div class="line-15"></div></div>
          <span class="bawang-merah">Bawang Merah</span>
        </div>
        <div class="rectangle-16">
          <div class="image-17"></div>
          <div class="line-18"></div>
          <span class="kentang">Kentang</span>
        </div>
        <div class="rectangle-19">
          <div class="image-1a"></div>
          <div class="line-1b"></div>
          <span class="brokoli">Brokoli</span>
        </div>
        <div class="rectangle-1c">
          <div class="image-1d"><div class="line-1e"></div></div>
          <span class="alpukat">Alpukat</span>
        </div>
      </div>
      <div class="flex-row-db">
        <div class="rectangle-1f">
          <div class="image-20"></div>
          <div class="line-21"></div>
          <span class="daun-bawang">Daun Bawang</span>
        </div>
        <div class="rectangle-22">
          <div class="image-23"><div class="line-24"></div></div>
          <span class="strawberry">Strawberry</span>
        </div>
        <div class="rectangle-25">
          <div class="image-26"></div>
          <div class="line-27"></div>
          <span class="jeruk">Jeruk</span>
        </div>
        <div class="rectangle-28">
          <div class="image-29"></div>
          <div class="line-2a"></div>
          <span class="anggur">Anggur</span>
        </div>
        <div class="rectangle-2b">
          <div class="image-2c"></div>
          <div class="line-2d"></div>
          <span class="jagung">Jagung</span>
        </div>
      </div>
    </div>
    <!-- Generated by Codia AI - https://codia.ai/ -->
  </body>
</html>
